version: '3.7'

services:
  bd:
    image: postgres:latest
    container_name: postgres-db-local
    restart: always
    user: postgres
    shm_size: 128mb
    secrets:
      - db_password
    environment:
      POSTGRES_DB: "ozon-route"
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 15432:5432

  cache:
    image: redis/redis-stack-server:latest
    container_name: redis-cache-local
    restart: always
    env_file:
      - .env
    volumes:
      - ~/Volumes/redis_volume:/data
    environment:
      REDIS_ARGS: "--appendonly yes --appendfsync everysec --rdbcompression yes --requirepass ${REDIS_PASSWORD} --user ${REDIS_USER} on >${REDIS_PASSWORD} ~* allcommands --user default off nopass nocommands"
    ports:
      - 6379:6379

secrets:
  db_password:
    file: secrets/Databases/Postgres/password.txt