version: '3.7'

services:
  database:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    user: postgres
    shm_size: 128mb
    env_file:
      - .env
    secrets:
      - db_password
    environment:
      POSTGRES_DB: "ozon-route"
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - ${PG_PORT}:5432

  cache:
    image: redis/redis-stack-server:latest
    container_name: redis-cache
    restart: always
    env_file:
      - .env
    volumes:
      - redis-data:/data
    environment:
      REDIS_ARGS: "--appendonly yes --appendfsync everysec --rdbcompression yes --requirepass ${REDIS_PASSWORD} --user ${REDIS_USER} on >${REDIS_PASSWORD} ~* allcommands --user default off nopass nocommands"
    ports:
      - ${REDIS_PORT}:6379

  # Not configuring xpack.seciruty and passwords for es & kibana, cause it's basically hell even for single node and requires Ssl certs.
  # Try it by yourself https://github.com/elastic/elasticsearch/blob/8.15/docs/reference/setup/install/docker/docker-compose.yml
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elastic-eng
    restart: always
    env_file:
      - .env
    environment:
      # - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - bootstrap.memory_lock=true
      # - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=false
      - discovery.type=single-node
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    networks:
      - elastic-bridge
    ports:
      - ${ES_PORT}:9200 

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    env_file:
      - .env
    environment:
      # - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      # - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_URL= http://localhost:9200
    volumes:
      - kibana-data:/usr/share/kibana/data
    networks:
      - elastic-bridge
    ports:
      - ${KIBANA_PORT}:5601
    links: ['elasticsearch']

volumes:
  redis-data:
    driver: local
  es-data01:
    driver: local
  kibana-data:
    driver: local

networks:
 elastic-bridge:
    driver: bridge

secrets:
  db_password:
    file: secrets/Databases/Postgres/password.txt